# Generated by Django 4.1 on 2022-09-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product name:')),
                ('image', models.ImageField(upload_to='./media/products/%Y-%m-%d/')),
                ('price', models.IntegerField(verbose_name='Price:')),
                ('description', models.TextField(verbose_name='Description:')),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
