# Generated by Django 4.1 on 2022-09-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='./main/static/products/%Y-%m-%d/'),
        ),
    ]
