# Generated by Django 4.1 on 2022-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='./main/media/products/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=15, verbose_name='Price:'),
        ),
    ]
