# Generated by Django 4.1 on 2022-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_image_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='products/%Y-%m-%d/'),
        ),
    ]
