# Generated by Django 4.1 on 2022-10-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('message', models.TextField(verbose_name='Message:')),
            ],
        ),
    ]
